changelog:
  exclude:
    labels:
    - no-changelog
    authors:
    - dependabot
  categories:
    - title: ":rocket: New Features"
      labels:
      - feat
    - title: ":bug: Bug Fixes"
      labels:
      - fix
    - title: ":broom: Code Refactoring"
      labels:
      - refactor
    - title: ":memo: Documentation"
      labels:
      - docs
    - title: ":lipstick: Code Style"
      labels:
      - style
    - title: ":racehorse: Performance Improvement"
      labels:
      - perf
    - title: ":white_check_mark: Tests"
      labels:
      - test
    - title: ":truck: Dependencies Management"
      labels:
      - chore
    - title: ":package: Builds Management"
      labels:
      - build
    - title: ":construction_worker: CI/CD"
      labels:
      - ci
    - title: ":rewind: Reverts Previous Changes"
      labels:
      - revert
    - title: Other Changes
      labels:
      - "*"
