{{- $webhookConfig := (merge (dict "name" "webhook" "module" "webhook") .) -}}

apiVersion: v1
kind: Secret
metadata:
  name: {{ include "liqo.prefixedName" $webhookConfig }}-certs
  labels:
    {{- include "liqo.labels" $webhookConfig | nindent 4 }}
    liqo.io/webhook: "true"
  annotations:
    liqo.io/webhook-service-name: {{ include "liqo.prefixedName" $webhookConfig }}
type: opaque
