{{- $controlPlaneConfig := (merge (dict "name" "remote-controlplane" "module" "authentication") .) -}}
{{- $crdReplicatorConfig := (merge (dict "name" "crd-replicator" "module" "dispatcher") .) -}}
{{- $ctrlManagerConfig := (merge (dict "name" "controller-manager" "module" "controller-manager") .) -}}


apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "liqo.prefixedName" $controlPlaneConfig }}
  labels:
    {{- include "liqo.labels" $controlPlaneConfig | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "liqo.prefixedName" $ctrlManagerConfig }}
    namespace: {{ .Release.Namespace }}
  - kind: ServiceAccount
    name: {{ include "liqo.prefixedName" $crdReplicatorConfig }}
    namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "liqo.prefixedName" $controlPlaneConfig }}
