{{- $telemetryConfig := (merge (dict "name" "telemetry" "module" "telemetry") .) -}}

{{- if .Values.telemetry.enabled }}

apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "liqo.prefixedName" $telemetryConfig }}
  labels:
    {{- include "liqo.labels" $telemetryConfig | nindent 4 }}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "liqo.prefixedName" $telemetryConfig }}
  labels:
    {{- include "liqo.labels" $telemetryConfig | nindent 4 }}
{{ .Files.Get (include "liqo.cluster-role-filename" (dict "prefix" ( include "liqo.prefixedName" $telemetryConfig))) }}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "liqo.prefixedName" $telemetryConfig }}
  labels:
    {{- include "liqo.labels" $telemetryConfig | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "liqo.prefixedName" $telemetryConfig }}
    namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "liqo.prefixedName" $telemetryConfig }}

{{- end }}
