apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: liqo-configmaps-reader
  namespace: liqo
rules:
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["networking.liqo.io"]
  resources: ["wggatewayservertemplates","wggatewayclienttemplates"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["ipam.liqo.io"]
  resources: ["networks"]
  verbs: ["list"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: liqo-shortcut-controller
  namespace: liqo-tenant-europe-cloud
rules:
- apiGroups: ["networking.liqo.io"]
  resources: ["configurations"]
  verbs: ["get", "list", "watch","create"]



---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: liqo-configmaps-reader-binding
  namespace: liqo
subjects:
- kind: User
  name: europe-cloud   # Assicurati che questo sia il nome corretto del service account
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: liqo-configmaps-reader


---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: liqo-shortcut-controller
  namespace: liqo-tenant-europe-cloud
subjects:
- kind: User
  name: europe-cloud   # Assicurati che questo sia il nome corretto del service account
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: liqo-shortcut-controller

