name: Greeting
on:
  pull_request_target:
    types:
      - opened

jobs:
  greeting:
    name: Issue a greeting comment upon PR
    runs-on: ubuntu-latest

    steps:
      - name: Issue the greeting comment
        uses: peter-evans/create-or-update-comment@v4
        with:
          token: ${{ secrets.CI_TOKEN }}
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            Hi @${{ github.event.pull_request.user.login }}. Thanks for your PR!

            I am @adamjensenbot.
            You can interact with me issuing a **slash command** in the first line of a **comment**.
            Currently, I understand the following commands:
            * `/rebase`:            Rebase this PR onto the master branch (You can add the option `test=true` to launch the tests
              when the rebase operation is completed)
            * `/merge`:             Merge this PR into the master branch
            * `/build`              Build Liqo components
            * `/test`               Launch the E2E and Unit tests
            * `/hold`, `/unhold`    Add/remove the hold label to prevent merging with /merge

            Make sure this PR appears in the **${{ github.event.repository.name }} changelog**, adding one of the following **labels**:
            * `feat`:          :rocket: New Feature
            * `fix`:           :bug: Bug Fix
            * `refactor`:      :broom: Code Refactoring
            * `docs`:          :memo: Documentation
            * `style`:         :lipstick: Code Style
            * `perf`:          :racehorse: Performance Improvement
            * `test`:          :white_check_mark: Tests
            * `chore`:         :truck: Dependencies Management
            * `build`:         :package: Builds Management
            * `ci`:            :construction_worker: CI/CD
            * `revert`:        :rewind: Reverts Previous Changes

